from pydantic import BaseModel, Field
from typing import List, Optional

class LinkedInSearchParams(BaseModel):
    # These fields will be generated by the LLM for LinkedIn search queries
    keywords: Optional[str] = Field(None, description="Keywords for LinkedIn search (e.g., job titles, skills, company names).")
    location: Optional[str] = Field(None, description="Geographic location for the search.")
    # Add more LinkedIn-specific search parameters as identified

class LinkedInRawProfile(BaseModel):
    # This model represents the raw data fetched directly from a LinkedIn public profile.
    # We'll add more fields here as we identify them from the LinkedIn API/data source.
    profile_url: str
    name: Optional[str] = None
    headline: Optional[str] = None
    location: Optional[str] = None
    industry: Optional[str] = None
    summary: Optional[str] = None
    experience: Optional[List[dict]] = None  # List of experience entries
    education: Optional[List[dict]] = None   # List of education entries
    skills: Optional[List[str]] = None
    # Add more fields as needed 